# -*- coding: utf-8 -*-
"""comprehensions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q99qwYqqmPXp54rWRw4vuNHFt_MgC-Qq

# List comprehensions
"""

lista = [x for x in range(0,10)]
print(lista)

lista = ['1', 'zero', 'Quatro']
lista = [x for x in lista]
print(lista)

lista_pares = [x for x in range(0,11) if x % 2 == 0]
print(lista_pares)

lista_auxiliar = [1,5,9]
lista = [x for x in range(1,11) if x not in lista_auxiliar]
print(lista)

lista = [x for x in range(-10,20) if x <= 10 if x > 0]
print(lista)

lista = [ x*2 for x in range(0,11)]
print(lista)

lista = [ str(x)[0] for x in range(0,21)]
print(lista)

lista = ['negativo' if x < 0 else 'positivo' for x in range(-3,4) ]
print(lista)

lista = [str(x) + ' par' if x % 2 == 0 else str(x) + ' impar'for x in range(2,11) ]
print(lista)

"""# Função Lambda"""

lista = [1,2,3,4,5,6,7,8,9]
lista = list(filter(lambda x: x % 2 ==0, lista))
print(lista)

# Criando uma matriz:
lista = [[x for x in range(1,5)] for y in range(1,5)]
print(lista)

lista = [[str(x) + str(y) for x in range(1,5)] for y in range(1,5)]
lista

[[str(x) + '*' + str(y) + '=' + str(x*y) for x in range(1,5)]  for y in range(1,11)]

"""# Atividades:

### 1) Crie uma lista com os seguintes números 1,10,6,7,8,10. Em seguida printe a soma destes números.
"""

tupla_1 = (1,10,6,7,8,10)
soma = 0

for x in tupla_1:
  soma += x

print('A soma total é : ',soma)

"""### 2) Crie uma lista e preencha ela com valores de 1 a 100. Em seguida printe esses valores."""

lista_2 = [x for x in range(1,101)]
print(lista_2)

# solução 2:
solucao_lista_2 = []
for i in range(1,101):
  solucao_lista_2.append(i)
print(solucao_lista_2)

"""### 3) Crie duas listas com os seguintes valores 30, 4, 43, 52, 65, -10 e 43, 2, 4, 76, 32, 65, 3. Agora faça a junção dessas listas, mas se houverem valores repetidos entre ambas, eles não podem ser incluidos duas vezes."""

lista_3_1 = [30,4,43,52,65,-10]
lista_3_2 = [43,2,4,76,32,65,3]

lista_3_juncao = lista_3_1

for x in lista_3_2:
  if x not in lista_3_1:
    lista_3_juncao.append(x)

print(lista_3_juncao)

"""### 4) Crie uma lista contendo o nome de todos os meses do ano. Em seguida receba por input o mês (número) em que você nasceu e mostre qual o nome do mês que você nasceu."""

# criamos uma tupla com os meses:
meses = ('janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro')

# variável que vai receber o mês de nascimento do usuário:
mes_nascimento = int(input('Qual mês que você nasceu? '))

print('Você nasceu em %s ' % (meses[mes_nascimento - 1]))

"""### 5) Crie uma lista contendo todos os dias (número) do mês em que você nasceu. Em seguida receba por input o dia (número) em que você nasceu e remova desta lista. Ao final mostre o conteúdo da lista."""

dias = []
for x in range(1,32):
  dias.append(x)

dia_nascimento = int(input('Qual dia que do mês você nasceu: '))
dias.remove(dia_nascimento)

print(dias)

"""### 6) Escolha três objetos de sua preferência e em seguida crie uma lista para armazenar o objeto e a sua função. Agora por input receba o nome desse objeto e imprima a sua função. Caso o objeto mão exista, informe ao usuário."""

objetos = {
    'cadeira' : 'serve para sentarmos',
    'monitor' : 'serve para visualizar o processamento',
    'mouse'   : 'server para realizar operações'
}

objeto_procurado = input('Digite o objeto: ')

if objeto_procurado in objetos:
  print(objetos[objeto_procurado])
else:
  print('Objeto não encontrado.')

"""### 7) Crie uma lista contendo todos os numeros negativos de -30 até -20. Printe essa lista."""

lista_7 = [x for x in range(-30,-19)]
print(lista_7)

"""### 8) Percorra os números de 4 a 100 e mantenha apenas aqueles divisíveis por 4."""

lista_8 = [x for x in range(4,101) if x % 4 == 0]
print(lista_8)

"""### 9) (DESAFIO) Crie uma lista contendo todos os números de 0 a 100, mas filtre, mantendo apenas os números que terminam com 0."""

lista_9 = [x for x in range(0,101) if str(x)[-1] =='0']
print(lista_9)

"""### 10) Percorra os números de 0 a 20 e crie um array, onde caso o número termine com zero o valor devera ser "0", caso contrario deverá ser "-"."""

lista_10 = ['0' if str(x)[-1] =='0' else '-' for x in range(0,21)]
print(lista_10)